version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: darts_web
    container_name: web
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - nginx_network
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: darts_app
    container_name: app
    volumes:
      - ./app:/app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge